import { build } from 'esbuild';
import { readFile, writeFile, mkdir, copyFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { validatePack } from '../app/validation.js';

const source = process.argv[2] || 'content/default.flagbook.json';
const destination = process.argv[3] || 'dist';
const pack = JSON.parse(await readFile(source, 'utf8'));
const result = validatePack(pack, source);
if (result.warnings.length) console.warn(result.warnings.join('\n'));
const bundle = await build({ entryPoints: ['app/main.js'], bundle: true, write: false, format: 'iife', target: ['safari16', 'chrome110'], minify: true, legalComments: 'inline' });
const html = await readFile('app/index.html', 'utf8');
const css = await readFile('app/style.css', 'utf8');
const template = await readFile('content-format/templates/new-play.yaml', 'utf8');
const runtimePackages = ['js-yaml', 'ajv', 'fast-uri', 'fast-deep-equal', 'json-schema-traverse'];
const licenses = [];
for (const name of runtimePackages) {
  const metadata = JSON.parse(await readFile(`node_modules/${name}/package.json`, 'utf8'));
  const license = await readFile(`node_modules/${name}/LICENSE`, 'utf8');
  licenses.push(`${name} ${metadata.version}\n${license}`);
}
const licenseText = licenses.join('\n\n----------------\n\n');
const scriptSafe = value => JSON.stringify(value).replaceAll('<', '\\u003c').replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029');
const output = html.replace('/*__APP_CSS__*/', () => css)
  .replace('__BUILT_IN_DATA__', () => scriptSafe(pack))
  .replace('__TEMPLATE_DATA__', () => scriptSafe(template))
  .replace('/*__APP_JS__*/', () => `/*!\n${licenseText.replaceAll('*/', '* /')}\n*/\n` + bundle.outputFiles[0].text.replaceAll('</script', '<\\/script'));
await mkdir(destination, { recursive: true });
await writeFile(`${destination}/Flagventures.html`, output);
await writeFile(`${destination}/index.html`, output);
await writeFile(`${destination}/NFL-FLAG完整战术.flagbook.json`, JSON.stringify(pack, null, 2));
await writeFile(`${destination}/第三方开源许可.txt`, licenseText);
// The online copy can be installed to a phone's home screen and opened offline at the field.
const icons = (await readdir('app/icons')).filter(name => name.endsWith('.png')).sort();
for (const icon of icons) await copyFile(`app/icons/${icon}`, `${destination}/${icon}`);
await writeFile(`${destination}/manifest.webmanifest`, JSON.stringify({
  name: 'Flagventures · 一起看懂跑位', short_name: 'Flagventures', lang: 'zh-CN',
  description: '和孩子一起认识腰旗橄榄球跑位。完整手册、关键帧讲解、自编战术导入，离线可用。',
  start_url: './', scope: './', display: 'standalone', background_color: '#f5f4ed', theme_color: '#193d32',
  icons: [
    { src: 'icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: 'icon-512.png', sizes: '512x512', type: 'image/png' },
    { src: 'icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
}, null, 2));
const version = createHash('sha256').update(output).digest('hex').slice(0, 12);
const offlineFiles = ['./', './index.html', './manifest.webmanifest', ...icons.map(icon => `./${icon}`)];
await writeFile(`${destination}/sw.js`, `// Generated by tools/build.mjs: keeps the app usable offline after the first visit.
const CACHE = 'flagventures-${version}';
const FILES = ${JSON.stringify(offlineFiles)};
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(key => key.startsWith('flagventures-') && key !== CACHE).map(key => caches.delete(key))))
    .then(() => self.clients.claim()));
});
// Answer from the cache at once (no signal at the field) and refresh that copy in the background.
self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  event.respondWith(caches.open(CACHE).then(async cache => {
    const cached = await cache.match(request, { ignoreSearch: true });
    const fresh = fetch(request).then(response => {
      if (response.ok && response.type === 'basic') cache.put(request, response.clone());
      return response;
    });
    if (!cached) return fresh;
    event.waitUntil(fresh.catch(() => {}));
    return cached;
  }));
});
`);
console.log(`已构建 ${pack.lessons.length} 个条目；HTML ${(Buffer.byteLength(output) / 1024 / 1024).toFixed(2)} MB → ${destination}`);
